logging:
  level: 4
providers:
  authorization: {}
  database:
    file: main.db.sqlite3
webServer:
  addr: :443
  sessions:
    defaultMaxAge: 3600
    encryptionSecret: ""
    rememberMaxAge: 2592000
  tls:
    certFile: ""
    keyFile: ""
