logging:
  level: 4
providers:
  authorization:
    base: dc=zekro,dc=de
    host: zekro.de
    port: "3893"
    usessl: "false"
  database:
    file: main.db.sqlite3
webServer:
  addr: :8080
  sessions:
    defaultMaxAge: 3600
    encryptionSecret: "test123"
    rememberMaxAge: 2592000
