logging:
  level: 5

webServer:
  addr: :8080
  sessions:
    defaultMaxAge:    3600
    encryptionSecret: badKeyButGoodEnoughForTesting
    rememberMaxAge:   2592000

providers:
  authorization: {}
  database:
    file: main.db.sqlite3