### DO NOT CHANGE THIS VALUES ###
title               = "vPlan"   #
base_url            = "/"       #
compile_sass        = true      #
highlight_code      = true      #
build_search_index  = true      #
#################################

[extra]
# Docs title
title = "vPlan2 Docs"
# Enable numbers on docs characters
book_number_chapters = true
# Location of the icon showed in avbar, 
# footer, login and logout screen
icon = "/media/logo/256x256.png"
# Icon hover / alt text
icon_alt_text = "Some Icon"

# Link to the API documentation
link_api_docs = "https://github.com/zekroTJA/vplan2019/blob/master/docs/api/api-docs.md"

############# DEBUG VARISABLES ##############
# Use static json files instead of boddies
# of HTTP requests
api_use_test_data = false
# Enable some tweaks using the testing
# LDAP server
use_test_ldap = false
# Custom timestamp from which data will be
# polled. Set this to "" to use today state.
use_test_vplan_date = ""