title = "vPlan"

description = "A book theme"

# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# Put all your custom variables here

title = "vPlan-Docs"
book_number_chapters = true
icon = "/media/logo/256x256.png"
icon_alt_text = "Some Icon"

<<<<<<< HEAD
# Enable/disable usage of test data
api_use_test_data = false
=======
link_api_docs = "https://github.com/zekroTJA/vplan2019/blob/master/docs/api/api-docs.md"

# Enable/disable usage of test data
api_use_test_data = true
>>>>>>> dev-zekro-fe
use_test_ldap = true
use_test_vplan_date = "2019-01-06T00:00:00Z"